class Player {
    constructor(name,surname,middlename, id) {
      this.name = name;
      this.middlename=middlename;
      this.surname=surname;
      this.id = id;
      this.fullname=this.surname + ' ' + this.name;
      //this.team=team
    }
  }
class Team{
    constructor(name){
        this.name=name;
        //this.coach=coach;
        //this.yearFoundation=yearFoundation;
    }
}
const allTeams=[
    new Team('30 PLUS BBC'),
    new Team('APR BBC'),
    new Team('ESPOIR'),
    new Team('PATRIOTS'),
    new Team('REG'),
    new Team('RP - IPRC-KIGALI BBC'),
    new Team('RP - IPRC Huye BBC'),
    new Team('RP IPRC MUSANZE'),
    new Team('RUSIZI Basketball Club'),
    new Team('Shoot For The Stars BBC'),
    new Team('Tigers BBC'),
    new Team('United Generations for Basketball'),
    new Team('UR-CMHS BBC'),
    new Team('UR BBC-MEN'),

];

  const allPlayers = [
    new Player('BIGWI','ABDOUL','DJABAL','#1'),
new Player('IKUNDABAYO','AIME','ERIC','#2'),
new Player('RUZIGANA','AIME','LANDRY','#3'),
new Player('NIYIGENA','AIME','PATRICK','#4'),
new Player('IRADUKUNDA','Alain','#5'),
new Player('IRERA','ALAIN','CLOVIS','#6'),
new Player('BERIMANA','Alain','David','#7'),
new Player('MICOMYIZA','Alain','Prince','#8'),
new Player('NDABIKUNZE','ALAIN','STEVE','#9'),
new Player('DUKUNDANE','Alba','#10'),
new Player('MUSABWA','Alex','#11'),
new Player('MUGABO','ALEXIS','#12'),
new Player('TWIZEYIMANA','ALEXIS','#13'),
new Player('RUZIGANDE','Ally','#14'),
new Player('HABYARIMANA','Alphonse','#15'),
new Player('UWIMANA','Alphonse','#16'),
new Player('NIYIGENA','AMZA','#17'),
new Player('MUGABE','Aristide','#18'),
new Player('SANGWE','ARISTIDE','#19'),
new Player('CUBAHIRO','Armand','#20'),
new Player('SANGWE','Armel','#21'),
new Player('KANAMUGIRE','ARNAUD','#22'),
new Player('AFRICA','AUBIN','#23'),
new Player('KASONGO','Aubin','Junior','#24'),
new Player('Joseph','BAHATI','WA','BAHATI','#25'),
new Player('BISA','NTAGWABIRA','BELIO','#26'),
new Player('BELECK','BELL','#27'),
new Player('NKANIRA','Bello','#28'),
new Player('NIJIMBERE','BENIT','#29'),
new Player('MUKENGERWA','Benjamin','#30'),
new Player('NIYONSABA','Bienvenu','#31'),
new Player('NZEYIMANA','BLAISE','#32'),
new Player('KASONGO','KASASA','BOBO','#33'),
new Player('NAHIMANA','Bonfils','#34'),
new Player('BIDELI','BONFILS','MIGUEL','#35'),
new Player('MBANZE','Brian','#36'),
new Player('MUGABO','BRIAN','#37'),
new Player('NYAMWASA','Bruno','#38'),
new Player('KALISA','BRYAN','#39'),
new Player('MURENZI','MUREGO','BRYAN','#40'),
new Player('WAMUKOTA','BUSHDUSHIME','C.','Pacifique','#41'),
new Player('ARAKAZA','CALEBMPANO','Cedric','#42'),
new Player('KABAYIZA','CHARLES','#43'),
new Player('NKURUNZIZA','CHARLES','#44'),
new Player('SANGWA','ARMAND','CHRIS','#45'),
new Player('GATAMBIRA','CHRISTIAN','#46'),
new Player('RUKUNDO','Claude','#47'),
new Player('MUNYANZIZA','Clement','#48'),
new Player('KAZUNGU','COLLIN','#49'),
new Player('NGABONZIZA','COPAIN','BLAISE','#50'),
new Player('NSABIMANA','Daniel','#51'),
new Player('KAREKEZI','DARCY','#52'),
new Player('BIKORIMANA','David','#53'),
new Player('NSENGIYUMKVA','DAVID','#54'),
new Player('NZAKARA','DAVIDAMANI','Deogratias','#55'),
new Player('NTWALI','DERRICK','#56'),
new Player('SAFARI','BAZIHIMA','Destin','#57'),
new Player('ABIMANA','DIDIER','#58'),
new Player('ISHIMWE','Didier','#59'),
new Player('BYIRINGIRO','DIEUDONNE','DIDIER','#60'),
new Player('MUGABO','DIFACE','#61'),
new Player('KWIZERA','DJAMAL','#62'),
new Player('KIMENYI','Donatien','#63'),
new Player('BIZIYAREMYE','DURRICK','#64'),
new Player('SHYENGO','ELITE','HONORE','#65'),
new Player('ISHIMWE','Elvis','#66'),
new Player('SANO','ELYSEE','#67'),
new Player('MBAYIHA','Emery','#68'),
new Player('NIYONSABA','EMILE','#69'),
new Player('HABUMUGISHA','Emmanuel','#70'),
new Player('IYAKAREMYE','Emmanuel','#71'),
new Player('KARIBU','EMMANUEL','#72'),
new Player('NTAYOMBA','EMMANUEL','#73'),
new Player('UMEADI','EMMANUEL','#74'),
new Player('ISEZERANO','Enock','#75'),
new Player('BIKANGISHO','ERIC','#76'),
new Player('MUHAYUMUKIZA','Eric','#77'),
new Player('MUNYANEZA','Eric','#78'),
new Player('SHEMA','Eric','#79'),
new Player('SHYAKA','Eric','#80'),
new Player('AGANZE','BAZIHIMA','Espoir','#81'),
new Player('RUTONESHA','ESPOIR','#82'),
new Player('ARAKARAMA','FABRICE','#83'),
new Player('ISHIMWE','FABRICE','#84'),
new Player('MUGIRANEZA','Fabrice','#85'),
new Player('MUHOZA','FABRICE','#86'),
new Player('GASASIRA','FARUKU','#87'),
new Player('IRUTINGABO','Fiston','#88'),
new Player('MWANABENE','FORTUNA','#89'),
new Player('TEKABAYIJA','FRANCIS','#90'),
new Player('EMMANUEL','FRANCOIS','#91'),
new Player('DUSHIMIMANA','Frank','#92'),
new Player('NTWARI','FRED','#93'),
new Player('KWIZERA','Freddy','#94'),
new Player('NTWARI','Gabin','#95'),
new Player('Gakuru','Ndahiro','#96'),
new Player('KAJEGUHAKWA','Gedega','#97'),
new Player('NIYIGENA','Gedeo','#98'),
new Player('IRAMBONA','GENTIL','#99'),
new Player('SORO','GEOFFREY','#100'),
new Player('NDEKEZI','GEUVARRA','#101'),
new Player('MUNYAKAZI','Gislain','#102'),
new Player('DUSHIMIMANA','Gladystone','#103'),
new Player('BAHI','BI','BALOU','GLINDAS','#104'),
new Player('SHEMA','GODSON','#105'),
new Player('NIJIMBERE','Guibert','#106'),
new Player('SHINGIRO','GUY','#107'),
new Player('IRAKOZE','H','Derrick','#108'),
new Player('IRUMVA','Heritier','#109'),
new Player('IKISHATSE','Herve','#110'),
new Player('MUNEZA','Ildephonse','#111'),
new Player('RUTAYISIRE','IMANI','#112'),
new Player('MUSONI','IRENE','#113'),
new Player('UWAYEZU','J.Brave','Heritier','#114'),
new Player('NTADOHOKA','J.EUDES','#115'),
new Player('MUHIZI','JACKSON','#116'),
new Player('BIKORIMANA','JEAN','AIME','#117'),
new Player('MUNEZERO','Jean','Aime','#118'),
new Player('KAYITARE','JEAN','AIMEE','#119'),
new Player('INKURUNZIZA','JEAN','CLAUDE','#120'),
new Player('MUDAHUNGA','Jean','Claude','#121'),
new Player('NIYUNGEHO','Jean de Dieu','#122'),
new Player('NTAGUNDUKA','Jean de Dieu','#123'),
new Player('UMUHOZA','Jean de Dieu','#124'),
new Player('RUCYERIMBERE','JEAN','MARIE','#125'),
new Player('IRADUKUNDA','JEAN','PAUL','#126'),
new Player('NDATIMANA','Jean','Paul','#127'),
new Player('NDOLI','Jean','Paul','#128'),
new Player('RUKUNDO','JEAN','PAUL','#129'),
new Player('SHYAKA','Jessy','#130'),
new Player('INKINDI','Jonathan','#131'),
new Player('YEZAKUZWE','JORDAN','#132'),
new Player('BUKURU','Joseph','#133'),
new Player('NTWALI','Josue','#134'),
new Player('TUYISHIME','JOSUE','#135'),
new Player('IRAKOZE','JULES','#136'),
new Player('MUHIRE','SANGANO','JULES','#137'),
new Player('MUTANGANA','Jules','Bruno','#138'),
new Player('KINZAMBA','AMBOLO','JUNIOR','#139'),
new Player('KUBWIMANA','K.','Ally','#140'),
new Player('RURANGIRWA','K.','Pascal','#141'),
new Player('KAMI','Kabange','#142'),
new Player('BUGINGO','Kabare','Hubert','#143'),
new Player('Elie','KAJEISHEMA','KEVIN','#144'),
new Player('IRUMVA','Landry','#145'),
new Player('NKUSI','LAURENT','#146'),
new Player('HITAYEZU','Leonard','#147'),
new Player('HAKIZIMANA','Lionnel','#148'),
new Player('NGENZAHAYO','MALIKI','#149'),
new Player('NGANDU','Mbanze','Bienvenu','#150'),
new Player('BYAMBO','MC','BRIGHT','#151'),
new Player('MUBERWA','Medard','#152'),
new Player('GITINYIRO','SERUGO','MODESTE','#153'),
new Player('KIZITO','MURENZI','ROMAIN','#154'),
new Player('HARERIMANA','MUSA','#155'),
new Player('MUNYESHURI','Mwenye','Prince','#156'),
new Player('NDIZEYE','N.','Dieudonne','#157'),
new Player('MUNYANDAMUTSA','n.','Sunny','#158'),
new Player('BAHOZA','NEHEMIENGAMIJE','NICOLAS','#159'),
new Player('NGOGA','NICOLAS','#160'),
new Player('SAFI','Normand','#161'),
new Player('BUZANGU','NTUMBA','MICKAEL','#162'),
new Player('DUSHIME','MBABAZI','Olivier','#163'),
new Player('IRADUKUNDA','Olivier','#164'),
new Player('KAMANZI','Olivier','#165'),
new Player('KAMILINDI','Olivier','#166'),
new Player('MUHIZI','OLIVIER','#167'),
new Player('NIYONSHUTI','OLIVIER','#168'),
new Player('SHYAKA','Olivier','#169'),
new Player('TURATSINZE','Olivier','#170'),
new Player('GAHAYIRO','PACIFIQUE','#171'),
new Player('HABYARIMANA','Pacifique','#172'),
new Player('MUTABAZI','PACIFIQUE','#173'),
new Player('NSENGIYUMVA','PACIFIQUE','#174'),
new Player('RURANGIRWA','PACIFIQUE','#175'),
new Player('ISHIMWE','Parfait','#176'),
new Player('NIYONKURU','Pascal','#177'),
new Player('HABIYAREMYE','Patrick','#178'),
new Player('KWIZERA','Patrick','#179'),
new Player('MURWANASHYAKA','PATRICK','#180'),
new Player('NDAHIRO','N','PATRICK','#181'),
new Player('NGABONZIZA','Patrick','#182'),
new Player('NIZEYIMANA','Patrick','#183'),
new Player('NSHIZIRUNGU','Patrick','#184'),
new Player('NZIRORERA','Patrick','#185'),
new Player('RUGAMBA','PATRICK','#186'),
new Player('RWEMA','PATRICK','#187'),
new Player('KABALISA','PAUL','#188'),
new Player('BAGABO','Phenias','#189'),
new Player('MWEBAZE','PHILBERT','#190'),
new Player('KUBANATUBANE','Philippe','#191'),
new Player('MUHIZI','PICASO','ARSENE','#192'),
new Player('MUDATENGUHA','PRINCE','#193'),
new Player('MUHIZI','Prince','#194'),
new Player('NSHIMIYIMANA','PRINCE','#195'),
new Player('EZE','PRINCE','NNAMDI','#196'),
new Player('MUDENDE','R.','Bruce','#197'),
new Player('NZITONDA','Raphael','#198'),
new Player('NDAHAYO','REMY','#199'),
new Player('NDONG','BIBANG','RMAULD','JEFFREY','#200'),
new Player('MUHIRE','ROBERT','#201'),
new Player('Cedric','RUTAZIGWA','GITORI','#202'),
new Player('NTWARI','Ryan','#203'),
new Player('KWIZERA','SACRÉ','#204'),
new Player('AMISI','SAIDI','#205'),
new Player('BUGINGO','SAMUEL','#206'),
new Player('IRADUKUNDA','Samuel','#207'),
new Player('NIYONSHUTI','Samuel','#208'),
new Player('BAHIRE','SAMUEL','BARNABAS','#209'),
new Player('UWIMANA','Sankara','#210'),
new Player('SAGAMBA','Sedar','#211'),
new Player('BIZIMANA','Serge','#212'),
new Player('KIRUSHA','Severin','#213'),
new Player('HABINEZA','Shaffi','#214'),
new Player('MUGIRANEZA','Shema','Theophile','#215'),
new Player('TOM','Shiva','#216'),
new Player('KALISA','SOUVENIR','#217'),
new Player('HAGUMINTWARI','Steven','#218'),
new Player('KAYITARE','MAMADOU','SYLLA','#219'),
new Player('NIYIBIZI','Theogene','#220'),
new Player('GATSINZI','Theoneste','#221'),
new Player('IRADUKUNDA','SHEMA','Thierry','#222'),
new Player('NKUNDWA','Thierry','#223'),
new Player('MUTEBA','TRESOR','#224'),
new Player('Uwitonze','Justin','#225'),
new Player('MUTABARUKA','Victoire','#226'),
new Player('UWIRINGIYIMANA','Vincent','#227'),
new Player('KWIZERA','WILSON','#228'),
new Player('NSHOBOZWABYOSENUMUKIZA','Wilson','#229'),
new Player('NIYUBAHWE','YAMIN','#230'),
new Player('BYIRINGIRO','Yannick','#231'),
new Player('NSHIMIYE','RWEMA','Yvan Axel','#232'),
new Player('ISHIMWE','Yves','#233'),
new Player('MUHIZI','YVES','','#234'),


  ];
  
  exports.getAllPlayers = () => {
    return allPlayers;
  }
  exports.getPlayerInfo = (playerName)=>{
      const getPlayer=allPlayers.filter(player=> (player.name===playerName));
      return getPlayer;
  }
  exports.getAllTeams = () => {
    return allTeams;
  }
